# Generated by Django 5.2.7 on 2025-12-22 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(help_text='Unique identifier: streak_7, breathing_10, etc.', max_length=100)),
                ('achievement_type', models.CharField(choices=[('streak', 'Streak'), ('breathing', 'Breathing'), ('stress_management', 'Stress Management'), ('pet_care', 'Pet Care'), ('milestone', 'Milestone')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for frontend', max_length=50)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='BreathingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise_type', models.CharField(default='box_breathing', help_text='Type: box_breathing, 4-7-8, etc.', max_length=50)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.CharField(choices=[('very_happy', 'Very Happy'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('calm', 'Calm')], max_length=20)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('stress_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('detected_by', models.CharField(help_text='What triggered detection: HR, HRV, grip, etc.', max_length=50)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Unlockable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlockable_id', models.CharField(max_length=100, unique=True)),
                ('unlockable_type', models.CharField(choices=[('accessory', 'Accessory'), ('environment', 'Environment'), ('pet_type', 'Pet Type'), ('color', 'Color Variant')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_level', models.PositiveIntegerField(default=1)),
                ('required_streak', models.PositiveIntegerField(blank=True, null=True)),
                ('required_achievement', models.CharField(blank=True, help_text='Required achievement_id', max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('cost_coins', models.PositiveIntegerField(default=0, help_text='Virtual currency cost')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(default=0, help_text='Virtual currency')),
                ('total_breathing_sessions', models.PositiveIntegerField(default=0)),
                ('total_stress_events_resolved', models.PositiveIntegerField(default=0)),
                ('average_hr_bpm', models.FloatField(blank=True, null=True)),
                ('average_hrv', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('haptic_feedback_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUnlockable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, help_text='Currently equipped/active')),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('cat', 'Cat'), ('fox', 'Fox'), ('dragon', 'Dragon'), ('dog', 'Dog'), ('rabbit', 'Rabbit')], default='cat', max_length=20)),
                ('name', models.CharField(default='Buddy', max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('calm', 'Calm'), ('worried', 'Worried'), ('stressed', 'Stressed'), ('excited', 'Excited'), ('sleeping', 'Sleeping')], default='calm', max_length=20)),
                ('mood_score', models.FloatField(default=0.5, help_text='0=worried, 1=happy', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('health', models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)])),
                ('last_fed', models.DateTimeField(blank=True, null=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessories', models.JSONField(blank=True, default=list, help_text='List of unlocked accessory IDs')),
                ('environment', models.CharField(default='default', help_text='Current environment/theme', max_length=50)),
            ],
            options={
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-ts']},
        ),
        migrations.AddField(
            model_name='reading',
            name='breathing_rate',
            field=models.FloatField(blank=True, help_text='Breathing rate per minute', null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='grip_force',
            field=models.FloatField(blank=True, help_text='Stress ball pressure in Newtons or arbitrary units', null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='posture_score',
            field=models.FloatField(blank=True, help_text='Posture quality score 0-1', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='reading',
            name='spo2',
            field=models.FloatField(blank=True, help_text='Blood oxygen saturation %', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='reading',
            name='hr_bpm',
            field=models.PositiveSmallIntegerField(help_text='Heart rate in beats per minute'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='hrv_rmssd',
            field=models.FloatField(blank=True, help_text='Heart rate variability (RMSSD)', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['user', '-ts'], name='api_reading_user_id_68fd41_idx'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breathingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stressevent',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stress_events', to='api.reading'),
        ),
        migrations.AddField(
            model_name='stressevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breathingsession',
            name='stress_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breathing_sessions', to='api.stressevent'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userunlockable',
            name='unlockable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unlockable'),
        ),
        migrations.AddField(
            model_name='userunlockable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virtualpet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_pet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('user', 'achievement_id')},
        ),
        migrations.AddIndex(
            model_name='stressevent',
            index=models.Index(fields=['user', '-ts'], name='api_stresse_user_id_fbf9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='stressevent',
            index=models.Index(fields=['user', 'resolved'], name='api_stresse_user_id_474e95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userunlockable',
            unique_together={('user', 'unlockable')},
        ),
    ]
